name: Release

on:
  push:
    # Publish `main` as Docker `edge` image.
    branches:
      - main

  # Run tests for any PRs.
  pull_request:

jobs:
  # Run tests.
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install systemd service
        run: |
          sudo mkdir -p /etc/conf.d
          sudo cp -vf tests/.env /etc/conf.d/docker-autoheal
          bash .ci/install.sh --local-install

      - name: Run tests
        run: |
          cd tests
          bash tests.sh

      - name: Uninstall systemd service
        run: |
          bash .ci/install.sh --local-install --uninstall

  # Build release.
  build:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}